allowBuilds:
  '@swc/core': set this to true or false
  esbuild: set this to true or false
  gifsicle: set this to true or false
  iltorb: set this to true or false
  jpegtran-bin: set this to true or false
  optipng-bin: set this to true or false
